version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sprinter_django
    container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command: /start

  postgres:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sprinter_postgres
    container_name: sprinter_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=mydb
      - POSTGRES_PASSWORD=mydb
      - POSTGRES_DB=mydb
    ports:
      - 5432
  redis:
    restart: always
    image: redis:6
    ports:
      - 6379
