# Generated by Django 3.2.9 on 2021-11-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparam',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Этот параметр влияет на цену товара?'),
        ),
    ]
