# Generated by Django 3.2.9 on 2022-01-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock',
            field=models.BooleanField(default=False, verbose_name='Есть в наличии?'),
        ),
    ]
