# Generated by Django 3.2.9 on 2021-12-26 08:29

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_basket_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='core.ProductOrder'),
        ),
    ]
