# Generated by Django 3.2.9 on 2021-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productcolor_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ManyToManyField(related_name='colors', to='core.Product'),
        ),
    ]
