# Generated by Django 3.2.9 on 2021-12-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211227_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.product'),
        ),
    ]
