# Generated by Django 3.2.9 on 2021-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
