# Generated by Django 3.2.9 on 2021-11-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productparam_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='product',
        ),
        migrations.AddField(
            model_name='promocode',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='core.Product'),
        ),
    ]
