# Generated by Django 3.2.9 on 2021-12-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_basket_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['created_at']},
        ),
    ]
