# Generated by Django 3.2.9 on 2021-11-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211130_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='product_param',
        ),
    ]
