# Generated by Django 3.2.9 on 2022-01-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коммент', 'verbose_name_plural': 'Комменты'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Цвет продукта', 'verbose_name_plural': 'Цветов продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картина продукта', 'verbose_name_plural': 'Картинки продукты'},
        ),
        migrations.AlterModelOptions(
            name='productparam',
            options={'verbose_name': 'Параметр продукта', 'verbose_name_plural': 'Параметры продукты'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Цена продукта', 'verbose_name_plural': 'Цены продукты'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'verbose_name': 'Файл отзыва', 'verbose_name_plural': 'Файлы отзывов'},
        ),
    ]
