# Generated by Django 3.2.9 on 2021-11-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_promocode_product'),
        ('core', '0006_comment_product'),
    ]

    operations = [
    ]
