# Generated by Django 3.2.9 on 2022-01-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220110_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ продукт', 'verbose_name_plural': 'Заказы продукты'},
        ),
    ]
