# Generated by Django 3.2.9 on 2021-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211226_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_price',
            field=models.FloatField(default=0),
        ),
    ]
