# Generated by Django 3.2.9 on 2021-11-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20211130_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='core.Color'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='product',
            field=models.ManyToManyField(blank=True, to='core.Product'),
        ),
    ]
