# Generated by Django 3.2.9 on 2022-01-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220110_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы   '},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Есть в наличии', 'In Stock'), ('Нет в наличии', 'Non Stock'), ('Скоро', 'Soon')], default='Есть в наличии', max_length=255),
        ),
    ]
