# Generated by Django 3.2.9 on 2021-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_catalog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(help_text='Title', max_length=255, unique=True),
        ),
    ]
