# Generated by Django 3.2.9 on 2021-11-30 19:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_catalog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='К какому каталогу относится этот каталог?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_catalogs', to='core.catalog'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(help_text='Название каталога', max_length=255, unique=True),
        ),
    ]
