# Generated by Django 3.2.9 on 2022-01-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20220112_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[('Есть в наличии', 'Есть в наличии'), ('Нет в наличии', 'Нет в наличии'), ('Скоро', 'Скоро')],
                default='Есть в наличии', max_length=255),
        ),
    ]
