# Generated by Django 3.2.9 on 2021-11-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211130_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='title_ru',
            field=models.CharField(help_text='Название каталога', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_uz',
            field=models.CharField(help_text='Название каталога', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='color',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='color',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
