# Generated by Django 3.2.9 on 2022-01-12 16:50

from django.db import migrations


def forward(apps, scheme_editor):
    Product = apps.get_model('core', 'Product')
    for product in Product.objects.all():
        product.catalogs.add(product.catalog)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_product_catalogs'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
