# Generated by Django 3.2.9 on 2021-11-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211130_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.color'),
            preserve_default=False,
        ),
    ]
