# Generated by Django 3.2.9 on 2021-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211130_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Payed', 'Payed'), ('Failure', 'Failure')], default='Waiting', max_length=255),
        ),
    ]
