# Generated by Django 3.2.9 on 2021-12-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_order_payment_status'),
        ('core', '0013_productorder_color'),
    ]

    operations = [
    ]
