# Generated by Django 3.2.9 on 2021-12-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20211201_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='title_en',
            field=models.CharField(help_text='Название каталога', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='color',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
