# Generated by Django 3.2.9 on 2022-01-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Есть в наличии', '1'), ('2', '2'), ('3', '3')], default='Есть в наличии', max_length=255),
        ),
    ]
