# Generated by Django 3.2.9 on 2021-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211201_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparam',
            name='is_static',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
