# Generated by Django 3.2.9 on 2021-12-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_review_reviewfileattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='file',
        ),
        migrations.AddField(
            model_name='reviewfileattachment',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.review'),
        ),
    ]
