# Generated by Django 3.2.9 on 2021-12-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_productparam_is_static'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparam',
            name='is_static',
        ),
    ]
