# Generated by Django 3.2.9 on 2022-01-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20220112_1923'),
        ('core', '0017_merge_20220112_1926'),
    ]

    operations = [
    ]
