# Generated by Django 3.2.9 on 2022-01-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20220112_1935'),
        ('core', '0018_merge_20220112_1947'),
    ]

    operations = [
    ]
