# Generated by Django 3.2.9 on 2021-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_productparam_is_static'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product_param',
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_param',
            field=models.ManyToManyField(to='core.ProductParam'),
        ),
    ]
