# Generated by Django 3.2.9 on 2022-01-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_catalog_is_active'),
        ('core', '0019_merge_20220112_1947'),
    ]

    operations = [
    ]
