# Generated by Django 3.2.9 on 2022-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20220112_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=100, verbose_name='Доступное количество'),
        ),
    ]
