# Generated by Django 3.2.9 on 2021-12-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_reviewfileattachment_reviewattachment'),
        ('core', '0021_auto_20211201_0837'),
    ]

    operations = [
    ]
