# Generated by Django 3.2.9 on 2021-12-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20211201_0848'),
        ('core', '0022_product_price'),
    ]

    operations = [
    ]
