# Generated by Django 3.2.9 on 2021-12-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_0022_merge_20211201_0848_0022_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparam',
            name='key_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productparam',
            name='key_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productparam',
            name='key_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productparam',
            name='value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productparam',
            name='value_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productparam',
            name='value_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
