# Generated by Django 3.2.9 on 2021-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20211201_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
