# Generated by Django 3.2.9 on 2021-12-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_productorder_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rating'),
        ),
    ]
