# Generated by Django 3.2.9 on 2021-12-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_review_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
