# Generated by Django 3.2.9 on 2021-12-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_productimages_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewAttachment',
            new_name='ReviewImage',
        ),
    ]
