# Generated by Django 3.2.9 on 2021-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_reviewattachment_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
