# Generated by Django 3.2.9 on 2021-12-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_delivered',
        ),
    ]
