# Generated by Django 3.2.9 on 2021-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_date_ordered_order_date_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
