# Generated by Django 3.2.9 on 2021-12-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_productimage_is_active'),
        ('core', '0032_order_price'),
    ]

    operations = [
    ]
