# Generated by Django 3.2.9 on 2021-12-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20211202_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.basket'),
        ),
    ]
