# Generated by Django 3.2.9 on 2021-12-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_order_basket'),
        ('core', '0034_alter_order_basket'),
    ]

    operations = [
    ]
