# Generated by Django 3.2.9 on 2021-12-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20211203_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='param',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.productparam'),
        ),
    ]
