# Generated by Django 3.2.9 on 2021-12-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211203_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparam',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='core.product'),
        ),
    ]
