# Generated by Django 3.2.9 on 2021-12-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_order_order_status'),
        ('core', '0039_alter_productparam_product'),
    ]

    operations = [
    ]
