# Generated by Django 3.2.9 on 2021-12-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20211204_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_price',
            new_name='price',
        ),
    ]
