# Generated by Django 3.2.9 on 2021-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_new_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
