# Generated by Django 3.2.9 on 2021-12-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_product_available_quantity'),
        ('core', '0043_alter_product_old_price'),
    ]

    operations = [
    ]
