# Generated by Django 3.2.9 on 2021-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_product_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
