# Generated by Django 3.2.9 on 2021-12-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_product_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcolor'),
        ),
    ]
