# Generated by Django 3.2.9 on 2021-12-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.review'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
    ]
