# Generated by Django 3.2.9 on 2021-12-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_rating_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
