# Generated by Django 3.2.9 on 2021-12-06 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country_area',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='captured_amount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='Hi', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('accept', 'Passed'), ('reject', 'Rejected'), ('review', 'Review')], default='unknown', max_length=10, verbose_name='fraud check'),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.CharField(default='Hi', max_length=255),
            preserve_default=False,
        ),
    ]
