# Generated by Django 3.2.9 on 2021-12-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20211206_2342'),
        ('core', '0052_delete_comment'),
    ]

    operations = [
    ]
