# Generated by Django 3.2.9 on 2021-12-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_product_is_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
