# Generated by Django 3.2.9 on 2021-12-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_catalog_image'),
        ('core', '0056_auto_20211208_2053'),
    ]

    operations = [
    ]
