# Generated by Django 3.2.9 on 2021-12-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_merge_0055_catalog_image_0056_auto_20211208_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/catalogs'),
        ),
    ]
