# Generated by Django 3.2.9 on 2021-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_catalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='NEW', max_length=50),
        ),
    ]
