# Generated by Django 3.2.9 on 2021-12-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='text',
        ),
    ]
