# Generated by Django 3.2.9 on 2021-12-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_rename_title_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='title_uz',
        ),
    ]
