# Generated by Django 3.2.9 on 2021-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
