# Generated by Django 3.2.9 on 2021-12-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_productcolor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
