# Generated by Django 3.2.9 on 2021-12-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
    ]
