# Generated by Django 3.2.9 on 2021-12-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='product',
        ),
        migrations.AddField(
            model_name='promocode',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.catalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Cancelled', 'Cancelled'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Opened', max_length=255),
        ),
    ]
