# Generated by Django 3.2.9 on 2021-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_region_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date_delivered',
            field=models.DateTimeField(null=True),
        ),
    ]
