# Generated by Django 3.2.9 on 2021-12-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_delivery_date_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='date_delivered',
        ),
    ]
