# Generated by Django 3.2.9 on 2021-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Cancelled', 'Cancelled'), ('In process', 'In process'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Opened', max_length=255),
        ),
    ]
