# Generated by Django 3.2.9 on 2021-12-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_product_discount'),
        ('core', '0084_alter_order_order_status'),
    ]

    operations = [
    ]
