# Generated by Django 3.2.9 on 2021-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_merge_20211219_1722'),
        ('core', '0085_merge_20211219_1728'),
    ]

    operations = [
    ]
