# Generated by Django 3.2.9 on 2021-12-23 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.order'),
            preserve_default=False,
        ),
    ]
