# Generated by Django 3.2.9 on 2022-01-12 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_backcall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backcall',
            options={'verbose_name': 'Запрос за звонок', 'verbose_name_plural': 'Запросы на звонки'},
        ),
    ]
