# Generated by Django 3.2.9 on 2021-12-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_en',
            field=models.TextField(null=True),
        ),
    ]
