# Generated by Django 3.2.9 on 2021-12-10 20:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20211211_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must begin with 998 and contain only 12 numbers', regex='^998\\d{9}$')])),
                ('zip_code', models.CharField(max_length=9)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
