# Generated by Django 3.2.9 on 2021-12-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_region_is_active'),
        ('user', '0012_auto_20211211_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
    ]
