# Generated by Django 3.2.9 on 2021-12-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_delivery_date_delivered'),
        ('user', '0013_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.region'),
            preserve_default=False,
        ),
    ]
